services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verysecurepassword
    ports:
      - "5432:5432" # Change the first set to change the outward facing port
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
