services:
  # postgres db
  db:
    container_name: fansbot_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fansbot
      POSTGRES_DB: fansbot
    volumes:
      - fansbot_db_data:/var/lib/postgresql
  # redis for communication
  redis:
    container_name: fansbot_redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - fansbot_redis_data:/var/lib/postgresql

volumes:
  fansbot_db_data:
  fansbot_redis_data: