services:
  # postgres db
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fansbot
      POSTGRES_DB: fansbot
    volumes:
      - fansbot_db_data:/var/lib/postgresql

volumes:
  fansbot_db_data: