DISCORD_TOKEN = ""

SERVER_ID = 0

MOD_ROLE_ID = 0
HELPER_ROLE_ID = 0

UNVERIFIED_ROLE_ID = 0
MEMBER_ROLE_ID = 0

RULES_CHANNEL_ID = 0

TICKET_CATEGORY_ID = 0

POLLS_CHANNEL_ID = 0

SOURCE_CODE_LINK = ""

SUPABASE_URL = ""
SUPABASE_KEY = ""
IS_TEST_ENV = False

MOD_LOG_CHANNEL_ID = 0

SPECIALS_CHANNEL_ID = 0
SPECIALS_ARCHIVE_TAG_NAME = "Archived"
MAIN_CATEGORY_ID = 0
OTHER_CATEGORY_ID = 0

SCHEDULES_CHANNEL_ID = 0
RADIO_SCHEDULES_THREAD_ID = 0


# these are aliases

discord_token = DISCORD_TOKEN
server_id = SERVER_ID
guild_id = SERVER_ID
GUILD_ID = SERVER_ID
mod_role_id = MOD_ROLE_ID
helper_role_id = HELPER_ROLE_ID
unverified_role_id = UNVERIFIED_ROLE_ID
member_role_id = MEMBER_ROLE_ID
rules_channel_id = RULES_CHANNEL_ID
ticket_category_id = TICKET_CATEGORY_ID
polls_channel_id = POLLS_CHANNEL_ID
source_code_link = SOURCE_CODE_LINK
